apiVersion: v1
kind: ServiceAccount
metadata:
  name: fast-sandbox-manager-role
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fast-sandbox-manager-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["sandbox.fast.io"]
  resources: ["sandboxes", "sandboxpools", "sandboxes/status", "sandboxpools/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fast-sandbox-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fast-sandbox-manager-role
subjects:
- kind: ServiceAccount
  name: fast-sandbox-manager-role
  namespace: default
