apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxPool
metadata:
  name: default-pool
  namespace: default
spec:
  agentTemplate:
    spec:
      containers:
      - image: fast-sandbox/agent:dev
        imagePullPolicy: IfNotPresent
        name: agent
  capacity:
    poolMax: 1
    poolMin: 1
  maxSandboxesPerPod: 5
  runtimeType: container
