apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxClaim
metadata:
  name: test-sandbox-poolref
  namespace: default
spec:
  image: "nginx:latest"
  cpu: "500m"
  memory: "1Gi"
  port: 8080
  poolRef:
    name: test-sandbox-pool
    namespace: default
