apiVersion: sandbox.fast.io/v1alpha1
kind: SandboxClaim
metadata:
  name: test-claim-with-pool
  namespace: default
spec:
  cpu: 100m
  image: fast-sandbox/agent:dev
  memory: 128Mi
  poolRef:
    name: test-sandbox-pool
    namespace: default
  port: 8080
