apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fast-sandbox-janitor
  namespace: default
  labels:
    app: fast-sandbox-janitor
spec:
  selector:
    matchLabels:
      app: fast-sandbox-janitor
  template:
    metadata:
      labels:
        app: fast-sandbox-janitor
    spec:
      serviceAccountName: fast-sandbox-manager-role
      tolerations:
      - operator: Exists
      containers:
      - name: janitor
        image: fast-sandbox/janitor:dev
        imagePullPolicy: IfNotPresent
        command: ["/workspace/janitor"]
        args: ["--scan-interval=2m"]
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: sock
          mountPath: /run/containerd/containerd.sock
        - name: fifo
          mountPath: /run/containerd/fifo
      volumes:
      - name: sock
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      - name: fifo
        hostPath:
          path: /run/containerd/fifo
          type: DirectoryOrCreate
