apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sandboxpools.sandbox.fast.io
spec:
  group: sandbox.fast.io
  names:
    kind: SandboxPool
    listKind: SandboxPoolList
    plural: sandboxpools
    singular: sandboxpool
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              capacity:
                type: object
                properties:
                  poolMin: {type: integer}
                  poolMax: {type: integer}
                  bufferMin: {type: integer}
                  bufferMax: {type: integer}
              maxSandboxesPerPod: {type: integer}
              runtimeType: {type: string}
              agentTemplate:
                type: object
                x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              currentPods: {type: integer}
              readyPods: {type: integer}
              totalAgents: {type: integer}
              idleAgents: {type: integer}
              busyAgents: {type: integer}
    subresources:
      status: {}
